---
title: "Randomization Results Section"
author: "Gjalt-Jorn Ygram Peters & Stefan Gruijters"
date: "`r format(Sys.time(), '%d %b %Y at %H:%M:%S');`"
output: 
  html_document: 
    toc: true
---

```{r preparation, echo=FALSE, results="hide", message=FALSE, error=FALSE, cache=FALSE}

################################################################################
################################################################################
### Configure basic settings
################################################################################
################################################################################

########################################################################
### Paths
########################################################################

### Add any relevant paths to this vector. The script will select the
### correct path itself.

basePathVector <- c("B:/Data/research/randomization/sample-sizes-for-randomization",
                    "");

########################################################################
### Set the variables with the paths
########################################################################

### Check which paths exist and set the first existing path in the list
### as the base path
basePath <- basePathVector[sapply(basePathVector, dir.exists)][1];

### Set the additional paths
workingPath <- basePath;
outputPath <- basePath;

########################################################################
### Packages
########################################################################

### Add path with RevoUtilsMath
.libPaths(c(.libPaths(), "C:/Program Files/Microsoft/MRO-3.3.2/library"));

require('userfriendlyscience', quietly = TRUE);
safeRequire('pander');
safeRequire('ggplot2');
safeRequire('reshape2');

########################################################################
### Settings
########################################################################

### Setting default knitting options
knitr::opts_chunk$set(echo=FALSE);
knitr::opts_chunk$set(comment=NA);
knitr::opts_chunk$set(dev="png", 
		  		            dev.args=list(type="cairo"),
			    	          dpi=100);
knitr::opts_chunk$set(fig.width=5);
knitr::opts_chunk$set(fig.height=5);
knitr::opts_chunk$set(cache=TRUE);

options(scipen=100);
options(figure_counter = TRUE);
options(table_counter = TRUE);

setFigCapNumbering();
setTabCapNumbering();

```

```{r fig.cap="Probability of one nuisance variable differing between groups with Cohen's d values of at most 0.1 (light green area), 0.2 (green area), 0.3 (yellow area), 0.4 (orange area), at most 0.5 (light red area) and more than 0.5 (red area) for sample sizes from 20-1000." }

  df <- data.frame(x = seq(10, 1000, 1),
                   d.1 = 1 - prob.randomizationSuccess(d=.1, n=seq(10, 1000, 1), nNuisanceVars = 1),
                   d.2 = 1 - prob.randomizationSuccess(d=.2, n=seq(10, 1000, 1), nNuisanceVars = 1),
                   d.3 = 1 - prob.randomizationSuccess(d=.3, n=seq(10, 1000, 1), nNuisanceVars = 1),
                   d.4 = 1 - prob.randomizationSuccess(d=.4, n=seq(10, 1000, 1), nNuisanceVars = 1),
                   d.5 = 1 - prob.randomizationSuccess(d=.5, n=seq(10, 1000, 1), nNuisanceVars = 1));

  ggplot(df, aes(x=x)) +
    geom_ribbon(aes(ymax = 1, ymin=d.1), fill="#008800", alpha=.2) +
    geom_ribbon(aes(ymax = d.1, ymin=d.2), fill="#008800", alpha=.33) +
    geom_ribbon(aes(ymax = d.2, ymin=d.3), fill="#FFBF00", alpha=.33) +
    geom_ribbon(aes(ymax = d.3, ymin=d.4), fill="#FF8F00", alpha=.33) +
    geom_ribbon(aes(ymax = d.4, ymin=d.5), fill="#FF4F00", alpha=.33) +
    geom_ribbon(aes(ymax = d.5, ymin=0), fill="#FF0F00", alpha=.33) +
    geom_line(aes(y=d.1), color="#008800", size=1) +
    geom_line(aes(y=d.2), color="#FFBF00", size=1) +
    geom_line(aes(y=d.3), color="#FF8F00", size=1) +
    geom_line(aes(y=d.4), color="#FF4F00", size=1) +
    geom_line(aes(y=d.5), color="#FF0F00", size=1) +
    geom_hline(yintercept = .05) +
    geom_vline(xintercept = min(df[df$d.2 <= .05, 'x'])) +
    geom_vline(xintercept = min(df[df$d.3 <= .05, 'x'])) +
    geom_vline(xintercept = min(df[df$d.4 <= .05, 'x'])) +
    geom_vline(xintercept = min(df[df$d.5 <= .05, 'x'])) +
    xlab("Total sample size") +
    ylab("Probability of non-equivalent groups") +
    ggtitle("One nuisance variable") +
    coord_cartesian(ylim=c(0,1)) +
    scale_x_continuous(breaks=seq(0, 1000, by=100),
                       sec.axis=dup_axis(breaks=c(min(df[df$d.2 <= .05, 'x']),
                                                  min(df[df$d.3 <= .05, 'x']),
                                                  min(df[df$d.4 <= .05, 'x']),
                                                  min(df[df$d.5 <= .05, 'x'])))) +
    theme_bw(base_size = 16);

ggsave(file.path(outputPath, "figure 1 - non-equivalence probability for 1 nuisance variable.png"),
       width = 14,
       height = 8,
       type='cairo-png');

```

```{r fig.cap="Probability of one or more of ten nuisance variables differing between groups with Cohen's d values of at most 0.1 (light green area), 0.2 (green area), 0.3 (yellow area), 0.4 (orange area), at most 0.5 (light red area) and more than 0.5 (red area) for sample sizes from 20-1000."}

  df <- data.frame(x = seq(10, 1000, 1),
                   d.1 = 1 - prob.randomizationSuccess(d=.1, n=seq(10, 1000, 1), nNuisanceVars = 10),
                   d.2 = 1 - prob.randomizationSuccess(d=.2, n=seq(10, 1000, 1), nNuisanceVars = 10),
                   d.3 = 1 - prob.randomizationSuccess(d=.3, n=seq(10, 1000, 1), nNuisanceVars = 10),
                   d.4 = 1 - prob.randomizationSuccess(d=.4, n=seq(10, 1000, 1), nNuisanceVars = 10),
                   d.5 = 1 - prob.randomizationSuccess(d=.5, n=seq(10, 1000, 1), nNuisanceVars = 10));

  ggplot(df, aes(x=x)) +
    geom_ribbon(aes(ymax = 1, ymin=d.1), fill="#008800", alpha=.2) +
    geom_ribbon(aes(ymax = d.1, ymin=d.2), fill="#008800", alpha=.33) +
    geom_ribbon(aes(ymax = d.2, ymin=d.3), fill="#FFBF00", alpha=.33) +
    geom_ribbon(aes(ymax = d.3, ymin=d.4), fill="#FF8F00", alpha=.33) +
    geom_ribbon(aes(ymax = d.4, ymin=d.5), fill="#FF4F00", alpha=.33) +
    geom_ribbon(aes(ymax = d.5, ymin=0), fill="#FF0F00", alpha=.33) +
    geom_line(aes(y=d.1), color="#008800", size=1) +
    geom_line(aes(y=d.2), color="#FFBF00", size=1) +
    geom_line(aes(y=d.3), color="#FF8F00", size=1) +
    geom_line(aes(y=d.4), color="#FF4F00", size=1) +
    geom_line(aes(y=d.5), color="#FF0F00", size=1) +
    geom_hline(yintercept = .05) +
    geom_vline(xintercept = min(df[df$d.2 <= .05, 'x'])) +
    geom_vline(xintercept = min(df[df$d.3 <= .05, 'x'])) +
    geom_vline(xintercept = min(df[df$d.4 <= .05, 'x'])) +
    geom_vline(xintercept = min(df[df$d.5 <= .05, 'x'])) +
    xlab("Total sample size") +
    ylab("Probability of non-equivalent groups") +
    ggtitle("Ten nuisance variables") +
    coord_cartesian(ylim=c(0,1)) +
    scale_x_continuous(breaks=seq(0, 1000, by=100),
                       sec.axis=dup_axis(breaks=c(min(df[df$d.2 <= .05, 'x']),
                                                  min(df[df$d.3 <= .05, 'x']),
                                                  min(df[df$d.4 <= .05, 'x']),
                                                  min(df[df$d.5 <= .05, 'x'])))) +
    theme_bw(base_size = 16);

ggsave(file.path(outputPath, "figure 2 - non-equivalence probability for 10 nuisance variables.png"),
       width = 14,
       height = 8,
       type='cairo-png');

```


```{r fig.cap="Probability of one or more of one hundred nuisance variables differing between groups with Cohen's d values of at most 0.1 (light green area), 0.2 (green area), 0.3 (yellow area), 0.4 (orange area), at most 0.5 (light red area) and more than 0.5 (red area) for sample sizes from 20-1000."}

  df <- data.frame(x = seq(10, 1000, 1),
                   d.1 = 1 - prob.randomizationSuccess(d=.1, n=seq(10, 1000, 1), nNuisanceVars = 100),
                   d.2 = 1 - prob.randomizationSuccess(d=.2, n=seq(10, 1000, 1), nNuisanceVars = 100),
                   d.3 = 1 - prob.randomizationSuccess(d=.3, n=seq(10, 1000, 1), nNuisanceVars = 100),
                   d.4 = 1 - prob.randomizationSuccess(d=.4, n=seq(10, 1000, 1), nNuisanceVars = 100),
                   d.5 = 1 - prob.randomizationSuccess(d=.5, n=seq(10, 1000, 1), nNuisanceVars = 100));

  ggplot(df, aes(x=x)) +
    geom_ribbon(aes(ymax = 1, ymin=d.1), fill="#008800", alpha=.2) +
    geom_ribbon(aes(ymax = d.1, ymin=d.2), fill="#008800", alpha=.33) +
    geom_ribbon(aes(ymax = d.2, ymin=d.3), fill="#FFBF00", alpha=.33) +
    geom_ribbon(aes(ymax = d.3, ymin=d.4), fill="#FF8F00", alpha=.33) +
    geom_ribbon(aes(ymax = d.4, ymin=d.5), fill="#FF4F00", alpha=.33) +
    geom_ribbon(aes(ymax = d.5, ymin=0), fill="#FF0F00", alpha=.33) +
    geom_line(aes(y=d.1), color="#008800", size=1) +
    geom_line(aes(y=d.2), color="#FFBF00", size=1) +
    geom_line(aes(y=d.3), color="#FF8F00", size=1) +
    geom_line(aes(y=d.4), color="#FF4F00", size=1) +
    geom_line(aes(y=d.5), color="#FF0F00", size=1) +
    geom_hline(yintercept = .05) +
    geom_vline(xintercept = min(df[df$d.3 <= .05, 'x'])) +
    geom_vline(xintercept = min(df[df$d.4 <= .05, 'x'])) +
    geom_vline(xintercept = min(df[df$d.5 <= .05, 'x'])) +
    xlab("Total sample size") +
    ylab("Probability of non-equivalent groups") +
    ggtitle("A hundred nuisance variables") +
    coord_cartesian(ylim=c(0,1)) +
    scale_x_continuous(breaks=seq(0, 1000, by=100),
                       sec.axis=dup_axis(breaks=c(min(df[df$d.3 <= .05, 'x']),
                                                  min(df[df$d.4 <= .05, 'x']),
                                                  min(df[df$d.5 <= .05, 'x'])))) +
    theme_bw(base_size = 16);

ggsave(file.path(outputPath, "figure 3 - non-equivalence probability for 100 nuisance variables.png"),
       width = 14,
       height = 8,
       type='cairo-png');


```

```{r tab.cap="Required sample size to achieve 99%, 95%, 90%, and 80% likelihood of randomization success (P(equivalence) or P(eq)), with non-equivalence defined as group differences exceeding Cohen's d = 0.1, 0.2, 0.3, 0.4 and 0.5, and assuming one, ten, or a hundred nuisance variables exist." }

  tableDf <- pwr.randomizationSuccess(d=seq(.1, .5, .1),
                                      nNuisanceVars = c(1, 10, 100),
                                      pRandomizationSuccess = c(.99, .95, .9, .8));

  table1 <- rbind(rep(NA, 5),
                  tableDf['Nuisance var: 1', , ],
                  rep(NA, 5),
                  tableDf['Nuisance var: 10', , ],
                  rep(NA, 5),
                  tableDf['Nuisance var: 100', , ]);

  rownames(table1) <- gsub("Equival. prob:", "  P(eq) = ", rownames(table1));
  colnames(table1) <- gsub("Nonequival. at: d=", "d =", colnames(table1));

  rownames(table1)[c(1, 6, 11)] <- paste0("**", c(1, 10, 100),
                                          " nuisance variable",
                                          c("", "s", "s"), "**");
  pander(table1, missing="");

  write.csv(table1,
            file.path(outputPath, "table 1.csv"),
            na="");

```

```{r}

  if (!file.exists(file.path(basePath, 'rpp_data.csv'))) {
    stop("The file 'rpp_data.csv' is not available. Please visit https://osf.io/fgjvw and download it (see https://osf.io/bhcsf for the codebook).");
  }

  ### Import data
  dat <- getData(file.path(basePath, 'rpp_data.csv'));
  cat("Read", nrow(dat), "studies.");
  
  ### Select two-cell designs
  dat <- dat[grep('^(t\\()|(F\\(1)', dat$Test.statistic..O.), ];
  cat("Selected", nrow(dat), "two-cell designs.");
  
  ### Convenient names for the sample size.
  dat$originalSampleSize <- as.numeric(dat$N..O.);
  dat$replicationSampleSize <- as.numeric(dat$N..R.);

  ### Remove missing values
  dat <- dat[, c('originalSampleSize', 'replicationSampleSize')];
  dat <- na.omit(dat);
  cat("Retained samples after removing missing values:", nrow(dat));
  
  ### Remove huge sample sizes
  cat("Removing", sum(dat$replicationSampleSize >= 1000),
      "samples of over 1000 participants,");
  dat <- dat[dat$replicationSampleSize < 1000 ,];

  dat$originalProbNonequivalence_d.2_1nvar <-
    1 - prob.randomizationSuccess(n = dat$originalSampleSize, dNonequivalence = .2, nNuisanceVars = 1);
  dat$originalProbNonequivalence_d.2_10nvar <-
    1 - prob.randomizationSuccess(n = dat$originalSampleSize, dNonequivalence = .2, nNuisanceVars = 10);
  dat$originalProbNonequivalence_d.2_100nvar <-
    1 - prob.randomizationSuccess(n = dat$originalSampleSize, dNonequivalence = .2, nNuisanceVars = 100);
  dat$originalProbNonequivalence_d.5_1nvar <-
    1 - prob.randomizationSuccess(n = dat$originalSampleSize, dNonequivalence = .5, nNuisanceVars = 1);
  dat$originalProbNonequivalence_d.5_10nvar <-
    1 - prob.randomizationSuccess(n = dat$originalSampleSize, dNonequivalence = .5, nNuisanceVars = 10);
  dat$originalProbNonequivalence_d.5_100nvar <-
    1 - prob.randomizationSuccess(n = dat$originalSampleSize, dNonequivalence = .5, nNuisanceVars = 100);

  dat$replicationProbNonequivalence_d.2_1nvar <-
    1 - prob.randomizationSuccess(n = dat$replicationSampleSize, dNonequivalence = .2, nNuisanceVars = 1);
  dat$replicationProbNonequivalence_d.2_10nvar <-
    1 - prob.randomizationSuccess(n = dat$replicationSampleSize, dNonequivalence = .2, nNuisanceVars = 10);
  dat$replicationProbNonequivalence_d.2_100nvar <-
    1 - prob.randomizationSuccess(n = dat$replicationSampleSize, dNonequivalence = .2, nNuisanceVars = 100);
  dat$replicationProbNonequivalence_d.5_1nvar <-
    1 - prob.randomizationSuccess(n = dat$replicationSampleSize, dNonequivalence = .5, nNuisanceVars = 1);
  dat$replicationProbNonequivalence_d.5_10nvar <-
    1 - prob.randomizationSuccess(n = dat$replicationSampleSize, dNonequivalence = .5, nNuisanceVars = 10);
  dat$replicationProbNonequivalence_d.5_100nvar <-
    1 - prob.randomizationSuccess(n = dat$replicationSampleSize, dNonequivalence = .5, nNuisanceVars = 100);

  dat[, grep('ProbNonequivalence', names(dat))] <- lapply(dat[, grep('ProbNonequivalence', names(dat))],
                                                          function(x) return(100*x));
  
  for (currentVarName in grep('ProbNonequivalence', names(dat), value=TRUE)) {
    pandoc.p('');
    pandoc.header(gsub('(.*)ProbNonequivalence_d.(.)_(.*)nvar', 'Likelihood of randomization failure for \\1 studies, assuming \\3 nuisance variables and a tolerance of d < 0.\\2', currentVarName), 3);
    pandoc.p('');
    pander(descr(dat[, currentVarName]));
    pandoc.p('');
  }
  
  
  longDatOriginal <- melt(c(dat[, grep('originalProbNonequivalence', names(dat))]));
  names(longDatOriginal) <- c('probability', 'parameters');
  longDatOriginal$n <- rep(dat$originalSampleSize, nrow(longDatOriginal)/ nrow(dat));
  longDatOriginal$d <- gsub('originalProbNonequivalence_d(\\..)_.*',
                            'd = \\1', longDatOriginal$parameters);
  longDatOriginal$nVar <- gsub('originalProbNonequivalence_d.._(.*)nvar',
                               'nVar = \\1', longDatOriginal$parameters);

  longDatReplication <- melt(c(dat[, grep('replicationProbNonequivalence', names(dat))]));
  names(longDatReplication) <- c('probability', 'parameters');
  longDatReplication$n <- rep(dat$replicationSampleSize, nrow(longDatReplication) / nrow(dat));
  longDatReplication$d <- gsub('replicationProbNonequivalence_d(\\..)_.*',
                            'd = \\1', longDatReplication$parameters);
  longDatReplication$nVar <- gsub('replicationProbNonequivalence_d.._(.*)nvar',
                               'nVar = \\1', longDatReplication$parameters);
  
  ggplot(longDatOriginal, aes(x = nVar,
                              y = probability,
                              group = d,
                              shape = d,
                              color = n)) +
    geom_point(size=5, alpha=.75,
               position=position_jitterdodge(jitter.width = .2,
                                             jitter.height = 2,
                                             dodge.width = .7)) +
    theme_bw(base_size = 20) +
    scale_color_continuous(low="#BBBBBB", high="#000000") +
    scale_x_discrete(labels=c("1",
                              "10",
                              "100")) +
    xlab("Number of nuisance variables") +
    ylab("Probability of randomization failure");

ggsave(file.path(outputPath, "figure 4 (old) - probability of randomization failure for original studies.png"), 
       width = 14,
       height = 10,
       type='cairo-png');
 
  ggplot(longDatReplication, aes(x = nVar,
                                 y = probability,
                                 group = d,
                                 shape = d,
                                 color = n)) +
    geom_point(size=5, alpha=.75,
               position=position_jitterdodge(jitter.width = .2,
                                             jitter.height = 2,
                                             dodge.width = .7)) +
    theme_bw(base_size = 20) +
    scale_color_continuous(low="#BBBBBB", high="#000000") +
    scale_x_discrete(labels=c("1",
                              "10",
                              "100")) +
    xlab("Number of nuisance variables") +
    ylab("Probability of randomization failure");
  
ggsave(file.path(outputPath, "figure 5 (old) - probability of randomization failure for replications.png"), 
       width = 14,
       height = 10,
       type='cairo-png');

### Hmm, I guess we could use facets to combine them.
  
    
longDatBoth <- rbind(longDatOriginal, longDatReplication);
longDatBoth$study <- c(rep("Original study", nrow(longDatOriginal)),
                       rep("Replication", nrow(longDatReplication)));

ggplot(longDatBoth, aes(x = nVar,
                        y = probability,
                        group = d,
                        shape = d,
                        fill = n)) +
  geom_point(size=5, alpha=.75,
             stroke = 1, color='black',
             position=position_jitterdodge(jitter.width = .2,
                                           jitter.height = 2,
                                           dodge.width = .7)) +
  theme_bw(base_size = 20) +
  scale_shape_manual(values=c(21, 24)) +
  scale_fill_continuous(low="#BBBBBB", high="#000000", limits=c(0, 500)) +
  scale_x_discrete(labels=c("1",
                            "10",
                            "100")) +
  guides(fill=guide_colorbar("N:", reverse=TRUE),
         shape=guide_legend("d:")) +
  theme(legend.key.height = unit(4, 'line')) +
  xlab("Number of nuisance variables") +
  ylab("Probability of randomization failure") +
  facet_grid(. ~ study);

ggsave(file.path(outputPath, "figure 4 - probability of randomization failure.png"), 
       width = 16,
       height = 8,
       type='cairo-png');

  
```

```{r}

pandoc.header("Randomization power examples", 2);

pandoc.p(paste("128 participants, robust effect:",
               formatCI(c(100*prob.randomizationSuccess(128, .5, 100),
                          100*prob.randomizationSuccess(128, .5, 10)),
                        digits=0, sep="%; ", suffix="%]")));

pandoc.p(paste("128 participants, subtle effect: ",
               formatCI(c(100*prob.randomizationSuccess(128, .2, 100),
                          100*prob.randomizationSuccess(128, .2, 10)),
                        digits=0, sep="%; ", suffix="%]")));

```
